// Keep the first 100 entries and their order stable: saved choices refer to indexes.
const englishQuotes = [
  // Steadiness
  'I move through today with a calm and steady mind.',
  'My strength grows through consistent, quiet action.',
  'I can be grounded even when life moves quickly.',
  'I choose a measured response over a rushed reaction.',
  'Each small promise I keep strengthens my trust in myself.',
  'I stay centered while opportunities unfold around me.',
  'My progress is steady, real, and worth respecting.',
  'I bring a clear mind to the things that matter.',
  'I have room to pause, think, and choose well.',
  'A stable life is built one thoughtful day at a time.',
  'I can face uncertainty without losing my balance.',
  'My calm is a strength I can return to at any moment.',
  'I protect my energy and direct it with intention.',
  'I trust the quiet work I do behind the scenes.',
  'I make grounded decisions that support my future.',
  'My pace is steady, and my direction is clear.',
  'I meet change with flexibility and inner stability.',
  'I can be gentle with myself and firm in my purpose.',
  'Every steady step makes the next one easier.',
  'I create peace by choosing what deserves my attention.',

  // Health
  'My body deserves care, rest, and nourishing choices.',
  'I listen to my body with respect and curiosity.',
  'Healthy habits grow from small choices I can repeat.',
  'Rest is a valuable part of the life I am building.',
  'I make time for movement that helps me feel alive.',
  'I care for my health with patience, not pressure.',
  'My wellbeing is worthy of a place in my plans.',
  'I choose routines that give me steady energy.',
  'I notice what helps me feel balanced and well.',
  'I can begin again with a caring choice today.',
  'I treat my body as a partner, not a problem.',
  'Sleep, nourishment, and movement support my goals.',
  'I give myself permission to recover and recharge.',
  'My health grows through attention and everyday care.',
  'I honor the limits that help me stay well.',
  'I welcome habits that support a clear and peaceful mind.',
  'I am learning to care for myself in lasting ways.',
  'A healthy life is built with kindness and consistency.',
  'I choose what supports my energy for the long run.',
  'I make space for both ambition and wellbeing.',

  // Affluence
  'I build financial security through clear, thoughtful choices.',
  'I welcome opportunities that match my skills and values.',
  'I can grow my resources with patience and intention.',
  'My work creates value, and I allow myself to receive value.',
  'I make room for abundance without losing my balance.',
  'I learn, earn, save, and grow at a sustainable pace.',
  'I am capable of making wise decisions with money.',
  'I notice opportunities and prepare myself to meet them.',
  'I can enjoy today while planning responsibly for tomorrow.',
  'My skills and good judgment help me build a fuller life.',
  'I grow wealth by caring for what I already have.',
  'I allow success to feel calm, healthy, and sustainable.',
  'I am open to new ways of creating useful work.',
  'I deserve fair reward for the value I bring.',
  'My financial future improves with each deliberate step.',
  'I can be generous and protect my own stability.',
  'I choose long-term freedom over short-term pressure.',
  'I am building a life with more options and ease.',
  'Prosperity can grow alongside integrity and peace.',
  'I trust myself to learn what I need for financial growth.',

  // Patience
  'I give meaningful things the time they need to grow.',
  'Patience helps me see choices that hurry would hide.',
  'I can wait without doubting my direction.',
  'My steady effort matters, even before results appear.',
  'I let progress take root before asking it to bloom.',
  'I am patient with myself while I practice and improve.',
  'A pause gives me space to respond with wisdom.',
  'I can trust the process and still take action today.',
  'I choose persistence over the pressure to be perfect.',
  'My timing does not need to match anyone else’s.',
  'I am allowed to grow slowly and grow well.',
  'I can hold a big vision and focus on one step.',
  'I meet delays with patience and a practical next move.',
  'I release urgency that does not serve me.',
  'I give my goals consistent care, not constant worry.',
  'Each day of practice is part of the result.',
  'I stay open while good work finds its rhythm.',
  'I can be hopeful without demanding instant proof.',
  'Patience makes room for clarity and better decisions.',
  'I trust what steady care can create over time.',

  // Presence and quiet confidence
  'I enter each room with calm confidence and respect.',
  'My presence is strong because I am at ease with myself.',
  'I speak clearly and let my words carry their weight.',
  'I do not need to rush to be noticed.',
  'I make space for others without shrinking myself.',
  'My quiet confidence comes from knowing my values.',
  'I listen fully and speak with intention.',
  'I can be warm, composed, and unmistakably myself.',
  'I bring steadiness to the people and places around me.',
  'I stand tall in my choices and stay open to learning.',
  'My energy is calm, focused, and welcoming.',
  'I carry myself with dignity in every setting.',
  'I can set boundaries with grace and confidence.',
  'I let my actions express the strength of my character.',
  'I am comfortable taking up the space I need.',
  'A calm voice can have a powerful effect.',
  'I trust my perspective and remain curious about others.',
  'I bring a steady presence to important moments.',
  'I lead with clarity, patience, and quiet strength.',
  'I belong wherever I choose to show up fully.',
] as const

// Short excerpts from the original texts. The source is shown with each quote.
const chineseQuotes = [
  { text: '上善若水。', source: '《道德经》第八章' },
  { text: '知足者富。', source: '《道德经》第三十三章' },
  { text: '重为轻根，静为躁君。', source: '《道德经》第二十六章' },
  { text: '千里之行，始于足下。', source: '《道德经》第六十四章' },
  { text: '静胜躁，寒胜热。', source: '《道德经》第四十五章' },
  { text: '知彼知己，百战不殆。', source: '《孙子兵法·谋攻》' },
  { text: '胜兵先胜而后求战。', source: '《孙子兵法·军形》' },
  { text: '不战而屈人之兵。', source: '《孙子兵法·谋攻》' },
  { text: '以虞待不虞者胜。', source: '《孙子兵法·谋攻》' },
  { text: '先为不可胜，以待敌之可胜。', source: '《孙子兵法·军形》' },
  { text: '志不强者智不达，言不信者行不果。', source: '《墨子·修身》' },
  { text: '贫则见廉，富则见义。', source: '《墨子·修身》' },
  { text: '务言而缓行，虽辩必不听。', source: '《墨子·修身》' },
  { text: '兼相爱，交相利。', source: '《墨子·兼爱中》' },
  { text: '兴天下之利，除天下之害。', source: '《墨子·兼爱下》' },
  { text: '没有调查，没有发言权。', source: '毛泽东《反对本本主义》' },
  { text: '调查就是解决问题。', source: '毛泽东《反对本本主义》' },
  { text: '排除万难，去争取胜利。', source: '毛泽东《愚公移山》' },
  { text: '自力更生。', source: '毛泽东《抗日战争胜利后的时局和我们的方针》' },
  { text: '只要你说得对，我们就改正。', source: '毛泽东《为人民服务》' },
  // Append only: persisted keep/remove choices use these positions as IDs.
  { text: '夫唯不争，故无尤。', source: '《道德经》第八章' },
  { text: '功成身退。', source: '《道德经》第九章' },
  { text: '有之以为利，无之以为用。', source: '《道德经》第十一章' },
  { text: '功成而不居。', source: '《道德经》第二章' },
  { text: '不自见，故明。', source: '《道德经》第二十二章' },
  { text: '不自是，故彰。', source: '《道德经》第二十二章' },
  { text: '不自伐，故有功。', source: '《道德经》第二十二章' },
  { text: '不自矜，故长。', source: '《道德经》第二十二章' },
  { text: '希言自然。', source: '《道德经》第二十三章' },
  { text: '曲则全。', source: '《道德经》第二十二章' },
  { text: '少则得，多则惑。', source: '《道德经》第二十二章' },
  { text: '知人者智，自知者明。', source: '《道德经》第三十三章' },
  { text: '胜人者有力，自胜者强。', source: '《道德经》第三十三章' },
  { text: '强行者有志。', source: '《道德经》第三十三章' },
  { text: '不失其所者久。', source: '《道德经》第三十三章' },
  { text: '柔弱胜刚强。', source: '《道德经》第三十六章' },
  { text: '大器晚成。', source: '《道德经》第四十一章' },
  { text: '大音希声。', source: '《道德经》第四十一章' },
  { text: '大象无形。', source: '《道德经》第四十一章' },
  { text: '知足不辱，知止不殆。', source: '《道德经》第四十四章' },
  { text: '清静为天下正。', source: '《道德经》第四十五章' },
  { text: '为学日益，为道日损。', source: '《道德经》第四十八章' },
  { text: '见小曰明，守柔曰强。', source: '《道德经》第五十二章' },
  { text: '知和曰常，知常曰明。', source: '《道德经》第五十五章' },
  { text: '和其光，同其尘。', source: '《道德经》第五十六章' },
  { text: '光而不耀。', source: '《道德经》第五十八章' },
  { text: '深根固柢。', source: '《道德经》第五十九章' },
  { text: '图难于其易，为大于其细。', source: '《道德经》第六十三章' },
  { text: '天下难事，必作于易。', source: '《道德经》第六十三章' },
  { text: '慎终如始，则无败事。', source: '《道德经》第六十四章' },
  { text: '一曰慈，二曰俭，三曰不敢为天下先。', source: '《道德经》第六十七章' },
  { text: '善战者不怒。', source: '《道德经》第六十八章' },
  { text: '自知不自见，自爱不自贵。', source: '《道德经》第七十二章' },
  { text: '天网恢恢，疏而不失。', source: '《道德经》第七十三章' },
  { text: '为而不争。', source: '《道德经》第八十一章' },

  { text: '知之者胜，不知者不胜。', source: '《孙子兵法·始计》' },
  { text: '将者，智、信、仁、勇、严也。', source: '《孙子兵法·始计》' },
  { text: '势者，因利而制权也。', source: '《孙子兵法·始计》' },
  { text: '攻其无备，出其不意。', source: '《孙子兵法·始计》' },
  { text: '多算胜，少算不胜。', source: '《孙子兵法·始计》' },
  { text: '兵贵胜，不贵久。', source: '《孙子兵法·作战》' },
  { text: '上兵伐谋。', source: '《孙子兵法·谋攻》' },
  { text: '知可以战与不可以战者胜。', source: '《孙子兵法·谋攻》' },
  { text: '上下同欲者胜。', source: '《孙子兵法·谋攻》' },
  { text: '不可胜在己，可胜在敌。', source: '《孙子兵法·军形》' },
  { text: '胜可知，而不可为。', source: '《孙子兵法·军形》' },
  { text: '善战者，立于不败之地。', source: '《孙子兵法·军形》' },
  { text: '以正合，以奇胜。', source: '《孙子兵法·兵势》' },
  { text: '奇正相生，如循环之无端。', source: '《孙子兵法·兵势》' },
  { text: '求之于势，不责于人。', source: '《孙子兵法·兵势》' },
  { text: '致人而不致于人。', source: '《孙子兵法·虚实》' },
  { text: '避实而击虚。', source: '《孙子兵法·虚实》' },
  { text: '水因地而制行，兵因敌而制胜。', source: '《孙子兵法·虚实》' },
  { text: '无所不备，则无所不寡。', source: '《孙子兵法·虚实》' },
  { text: '以治待乱，以静待哗。', source: '《孙子兵法·军争》' },
  { text: '以近待远，以佚待劳。', source: '《孙子兵法·军争》' },
  { text: '智者之虑，必杂于利害。', source: '《孙子兵法·九变》' },
  { text: '无恃其不来，恃吾有以待之。', source: '《孙子兵法·九变》' },
  { text: '进不求名，退不避罪。', source: '《孙子兵法·地形》' },
  { text: '合于利而动，不合于利而止。', source: '《孙子兵法·九地》' },
  { text: '料敌制胜，计险厄远近。', source: '《孙子兵法·地形》' },
  { text: '围地则谋，死地则战。', source: '《孙子兵法·九地》' },
  { text: '非利不动，非得不用，非危不战。', source: '《孙子兵法·火攻》' },
  { text: '明主慎之，良将警之。', source: '《孙子兵法·火攻》' },
  { text: '先知者，不可取于鬼神。', source: '《孙子兵法·用间》' },

  { text: '士虽有学，而行为本焉。', source: '《墨子·修身》' },
  { text: '置本不安者，无务丰末。', source: '《墨子·修身》' },
  { text: '事无终始，无务多业。', source: '《墨子·修身》' },
  { text: '君子察迩，修身也。', source: '《墨子·修身》' },
  { text: '君子力事日强。', source: '《墨子·修身》' },
  { text: '生则见爱，死则见哀。', source: '《墨子·修身》' },
  { text: '本不固者，末必几。', source: '《墨子·修身》' },
  { text: '源浊者流不清。', source: '《墨子·修身》' },
  { text: '名不徒生，而誉不自长。', source: '《墨子·修身》' },
  { text: '慧者心辩而不繁说。', source: '《墨子·修身》' },
  { text: '多力而不伐功。', source: '《墨子·修身》' },
  { text: '言无务为多而务为智。', source: '《墨子·修身》' },
  { text: '名不可简而成也，誉不可巧而立也。', source: '《墨子·修身》' },
  { text: '君子以身戴行者也。', source: '《墨子·修身》' },
  { text: '行不信者名必耗。', source: '《墨子·修身》' },
  { text: '国有贤良之士众，则国家之治厚。', source: '《墨子·尚贤上》' },
  { text: '厚乎德行，辩乎言谈，博乎道术。', source: '《墨子·尚贤上》' },
  { text: '举公义，辟私怨。', source: '《墨子·尚贤上》' },
  { text: '官无常贵，而民无终贱。', source: '《墨子·尚贤上》' },
  { text: '有能则举之，无能则下之。', source: '《墨子·尚贤上》' },
  { text: '得士则谋不困，体不劳。', source: '《墨子·尚贤上》' },
  { text: '尚贤者，政之本也。', source: '《墨子·尚贤上》' },
  { text: '因其国家，去其无用，足以倍之。', source: '《墨子·节用上》' },
  { text: '用财不费，民德不劳。', source: '《墨子·节用上》' },
  { text: '去无用之务，行圣王之道。', source: '《墨子·节用上》' },
  { text: '使各从事其所能。', source: '《墨子·节用中》' },
  { text: '加费不加民利则止。', source: '《墨子·节用中》' },
  { text: '足以充虚继气，强股肱，使耳目聪明，则止。', source: '《墨子·节用中》' },
  { text: '欲天下之富，而恶其贫。', source: '《墨子·兼爱中》' },
  { text: '欲天下之治，而恶其乱。', source: '《墨子·兼爱中》' },

  { text: '虚心使人进步，骄傲使人落后。', source: '毛泽东《在中国共产党第八届全国代表大会上的开幕词》' },
  { text: '情况是在不断地变化。', source: '毛泽东《在中国共产党全国宣传工作会议上的讲话》' },
  { text: '我们看事情必须要看它的实质。', source: '毛泽东《星星之火，可以燎原》' },
  { text: '自己动手，克服困难。', source: '毛泽东《开展根据地的减租、生产和拥政爱民运动》' },
  { text: '我们应该老老实实地办事。', source: '毛泽东《在中国共产党全国宣传工作会议上的讲话》' },
] as const

export const quotes: readonly string[] = [
  ...englishQuotes,
  ...chineseQuotes.map((quote) => quote.text),
]

export function quoteSource(id: number): string | undefined {
  return chineseQuotes[id - englishQuotes.length]?.source
}

export function quoteForDate(date: string, rejectedIds: number[]) {
  const [year, month, day] = date.split('-').map(Number)
  const dayNumber = Math.floor(Date.UTC(year, month - 1, day) / 86_400_000)
  const rejected = new Set(rejectedIds)
  const isChineseDay = dayNumber % 2 === 0
  const preferredStart = isChineseDay ? englishQuotes.length : 0
  const preferredLength = isChineseDay ? chineseQuotes.length : englishQuotes.length
  const otherStart = isChineseDay ? 0 : englishQuotes.length
  const otherLength = isChineseDay ? englishQuotes.length : chineseQuotes.length
  const dayInLanguage = Math.floor(dayNumber / 2)

  for (const [start, length] of [[preferredStart, preferredLength], [otherStart, otherLength]]) {
    const firstIndex = ((dayInLanguage * 37) % length + length) % length
    for (let offset = 0; offset < length; offset++) {
      const id = start + (firstIndex + offset) % length
      if (!rejected.has(id)) return { id, text: quotes[id], source: quoteSource(id) }
    }
  }
  return null
}
