// Keep the first 100 entries and their order stable: saved choices refer to indexes.
const englishQuotes = [
  // Steadiness
  'I move through today with a calm and steady mind.',
  'My strength grows through consistent, quiet action.',
  'I can be grounded even when life moves quickly.',
  'I choose a measured response over a rushed reaction.',
  'Each small promise I keep strengthens my trust in myself.',
  'I stay centered while opportunities unfold around me.',
  'My progress is steady, real, and worth respecting.',
  'I bring a clear mind to the things that matter.',
  'I have room to pause, think, and choose well.',
  'A stable life is built one thoughtful day at a time.',
  'I can face uncertainty without losing my balance.',
  'My calm is a strength I can return to at any moment.',
  'I protect my energy and direct it with intention.',
  'I trust the quiet work I do behind the scenes.',
  'I make grounded decisions that support my future.',
  'My pace is steady, and my direction is clear.',
  'I meet change with flexibility and inner stability.',
  'I can be gentle with myself and firm in my purpose.',
  'Every steady step makes the next one easier.',
  'I create peace by choosing what deserves my attention.',

  // Health
  'My body deserves care, rest, and nourishing choices.',
  'I listen to my body with respect and curiosity.',
  'Healthy habits grow from small choices I can repeat.',
  'Rest is a valuable part of the life I am building.',
  'I make time for movement that helps me feel alive.',
  'I care for my health with patience, not pressure.',
  'My wellbeing is worthy of a place in my plans.',
  'I choose routines that give me steady energy.',
  'I notice what helps me feel balanced and well.',
  'I can begin again with a caring choice today.',
  'I treat my body as a partner, not a problem.',
  'Sleep, nourishment, and movement support my goals.',
  'I give myself permission to recover and recharge.',
  'My health grows through attention and everyday care.',
  'I honor the limits that help me stay well.',
  'I welcome habits that support a clear and peaceful mind.',
  'I am learning to care for myself in lasting ways.',
  'A healthy life is built with kindness and consistency.',
  'I choose what supports my energy for the long run.',
  'I make space for both ambition and wellbeing.',

  // Affluence
  'I build financial security through clear, thoughtful choices.',
  'I welcome opportunities that match my skills and values.',
  'I can grow my resources with patience and intention.',
  'My work creates value, and I allow myself to receive value.',
  'I make room for abundance without losing my balance.',
  'I learn, earn, save, and grow at a sustainable pace.',
  'I am capable of making wise decisions with money.',
  'I notice opportunities and prepare myself to meet them.',
  'I can enjoy today while planning responsibly for tomorrow.',
  'My skills and good judgment help me build a fuller life.',
  'I grow wealth by caring for what I already have.',
  'I allow success to feel calm, healthy, and sustainable.',
  'I am open to new ways of creating useful work.',
  'I deserve fair reward for the value I bring.',
  'My financial future improves with each deliberate step.',
  'I can be generous and protect my own stability.',
  'I choose long-term freedom over short-term pressure.',
  'I am building a life with more options and ease.',
  'Prosperity can grow alongside integrity and peace.',
  'I trust myself to learn what I need for financial growth.',

  // Patience
  'I give meaningful things the time they need to grow.',
  'Patience helps me see choices that hurry would hide.',
  'I can wait without doubting my direction.',
  'My steady effort matters, even before results appear.',
  'I let progress take root before asking it to bloom.',
  'I am patient with myself while I practice and improve.',
  'A pause gives me space to respond with wisdom.',
  'I can trust the process and still take action today.',
  'I choose persistence over the pressure to be perfect.',
  'My timing does not need to match anyone else’s.',
  'I am allowed to grow slowly and grow well.',
  'I can hold a big vision and focus on one step.',
  'I meet delays with patience and a practical next move.',
  'I release urgency that does not serve me.',
  'I give my goals consistent care, not constant worry.',
  'Each day of practice is part of the result.',
  'I stay open while good work finds its rhythm.',
  'I can be hopeful without demanding instant proof.',
  'Patience makes room for clarity and better decisions.',
  'I trust what steady care can create over time.',

  // Presence and quiet confidence
  'I enter each room with calm confidence and respect.',
  'My presence is strong because I am at ease with myself.',
  'I speak clearly and let my words carry their weight.',
  'I do not need to rush to be noticed.',
  'I make space for others without shrinking myself.',
  'My quiet confidence comes from knowing my values.',
  'I listen fully and speak with intention.',
  'I can be warm, composed, and unmistakably myself.',
  'I bring steadiness to the people and places around me.',
  'I stand tall in my choices and stay open to learning.',
  'My energy is calm, focused, and welcoming.',
  'I carry myself with dignity in every setting.',
  'I can set boundaries with grace and confidence.',
  'I let my actions express the strength of my character.',
  'I am comfortable taking up the space I need.',
  'A calm voice can have a powerful effect.',
  'I trust my perspective and remain curious about others.',
  'I bring a steady presence to important moments.',
  'I lead with clarity, patience, and quiet strength.',
  'I belong wherever I choose to show up fully.',
] as const

// IDs are persisted on devices and in cloud snapshots. Retired entries stay as
// empty slots so saved choices for other quotes never point to different text.
const chineseQuotes = [
  null, null, null, null, null,
  { text: '知彼知己，百战不殆。', source: '《孙子兵法·谋攻》' },
  { text: '胜兵先胜而后求战。', source: '《孙子兵法·军形》' },
  { text: '不战而屈人之兵。', source: '《孙子兵法·谋攻》' },
  { text: '以虞待不虞者胜。', source: '《孙子兵法·谋攻》' },
  { text: '先为不可胜，以待敌之可胜。', source: '《孙子兵法·军形》' },
  { text: '志不强者智不达，言不信者行不果。', source: '《墨子·修身》' },
  { text: '贫则见廉，富则见义。', source: '《墨子·修身》' },
  { text: '务言而缓行，虽辩必不听。', source: '《墨子·修身》' },
  { text: '兼相爱，交相利。', source: '《墨子·兼爱中》' },
  { text: '兴天下之利，除天下之害。', source: '《墨子·兼爱下》' },
  { text: '没有调查，没有发言权。', source: '毛泽东《反对本本主义》' },
  { text: '调查就是解决问题。', source: '毛泽东《反对本本主义》' },
  { text: '排除万难，去争取胜利。', source: '毛泽东《愚公移山》' },
  { text: '自力更生。', source: '毛泽东《抗日战争胜利后的时局和我们的方针》' },
  { text: '只要你说得对，我们就改正。', source: '毛泽东《为人民服务》' },
  // These 35 retired IDs remain empty; new quotes are appended below.
  null, null, null, null, null, null, null,
  null, null, null, null, null, null, null,
  null, null, null, null, null, null, null,
  null, null, null, null, null, null, null,
  null, null, null, null, null, null, null,

  { text: '知之者胜，不知者不胜。', source: '《孙子兵法·始计》' },
  { text: '将者，智、信、仁、勇、严也。', source: '《孙子兵法·始计》' },
  { text: '势者，因利而制权也。', source: '《孙子兵法·始计》' },
  { text: '攻其无备，出其不意。', source: '《孙子兵法·始计》' },
  { text: '多算胜，少算不胜。', source: '《孙子兵法·始计》' },
  { text: '兵贵胜，不贵久。', source: '《孙子兵法·作战》' },
  { text: '上兵伐谋。', source: '《孙子兵法·谋攻》' },
  { text: '知可以战与不可以战者胜。', source: '《孙子兵法·谋攻》' },
  { text: '上下同欲者胜。', source: '《孙子兵法·谋攻》' },
  { text: '不可胜在己，可胜在敌。', source: '《孙子兵法·军形》' },
  { text: '胜可知，而不可为。', source: '《孙子兵法·军形》' },
  { text: '善战者，立于不败之地。', source: '《孙子兵法·军形》' },
  { text: '以正合，以奇胜。', source: '《孙子兵法·兵势》' },
  { text: '奇正相生，如循环之无端。', source: '《孙子兵法·兵势》' },
  { text: '求之于势，不责于人。', source: '《孙子兵法·兵势》' },
  { text: '致人而不致于人。', source: '《孙子兵法·虚实》' },
  { text: '避实而击虚。', source: '《孙子兵法·虚实》' },
  { text: '水因地而制行，兵因敌而制胜。', source: '《孙子兵法·虚实》' },
  { text: '无所不备，则无所不寡。', source: '《孙子兵法·虚实》' },
  { text: '以治待乱，以静待哗。', source: '《孙子兵法·军争》' },
  { text: '以近待远，以佚待劳。', source: '《孙子兵法·军争》' },
  { text: '智者之虑，必杂于利害。', source: '《孙子兵法·九变》' },
  { text: '无恃其不来，恃吾有以待之。', source: '《孙子兵法·九变》' },
  { text: '进不求名，退不避罪。', source: '《孙子兵法·地形》' },
  { text: '合于利而动，不合于利而止。', source: '《孙子兵法·九地》' },
  { text: '料敌制胜，计险厄远近。', source: '《孙子兵法·地形》' },
  { text: '围地则谋，死地则战。', source: '《孙子兵法·九地》' },
  { text: '非利不动，非得不用，非危不战。', source: '《孙子兵法·火攻》' },
  { text: '明主慎之，良将警之。', source: '《孙子兵法·火攻》' },
  { text: '先知者，不可取于鬼神。', source: '《孙子兵法·用间》' },

  { text: '士虽有学，而行为本焉。', source: '《墨子·修身》' },
  { text: '置本不安者，无务丰末。', source: '《墨子·修身》' },
  { text: '事无终始，无务多业。', source: '《墨子·修身》' },
  { text: '君子察迩，修身也。', source: '《墨子·修身》' },
  { text: '君子力事日强。', source: '《墨子·修身》' },
  { text: '生则见爱，死则见哀。', source: '《墨子·修身》' },
  { text: '本不固者，末必几。', source: '《墨子·修身》' },
  { text: '源浊者流不清。', source: '《墨子·修身》' },
  { text: '名不徒生，而誉不自长。', source: '《墨子·修身》' },
  { text: '慧者心辩而不繁说。', source: '《墨子·修身》' },
  { text: '多力而不伐功。', source: '《墨子·修身》' },
  { text: '言无务为多而务为智。', source: '《墨子·修身》' },
  { text: '名不可简而成也，誉不可巧而立也。', source: '《墨子·修身》' },
  { text: '君子以身戴行者也。', source: '《墨子·修身》' },
  { text: '行不信者名必耗。', source: '《墨子·修身》' },
  { text: '国有贤良之士众，则国家之治厚。', source: '《墨子·尚贤上》' },
  { text: '厚乎德行，辩乎言谈，博乎道术。', source: '《墨子·尚贤上》' },
  { text: '举公义，辟私怨。', source: '《墨子·尚贤上》' },
  { text: '官无常贵，而民无终贱。', source: '《墨子·尚贤上》' },
  { text: '有能则举之，无能则下之。', source: '《墨子·尚贤上》' },
  { text: '得士则谋不困，体不劳。', source: '《墨子·尚贤上》' },
  { text: '尚贤者，政之本也。', source: '《墨子·尚贤上》' },
  { text: '因其国家，去其无用，足以倍之。', source: '《墨子·节用上》' },
  { text: '用财不费，民德不劳。', source: '《墨子·节用上》' },
  { text: '去无用之务，行圣王之道。', source: '《墨子·节用上》' },
  { text: '使各从事其所能。', source: '《墨子·节用中》' },
  { text: '加费不加民利则止。', source: '《墨子·节用中》' },
  { text: '足以充虚继气，强股肱，使耳目聪明，则止。', source: '《墨子·节用中》' },
  { text: '欲天下之富，而恶其贫。', source: '《墨子·兼爱中》' },
  { text: '欲天下之治，而恶其乱。', source: '《墨子·兼爱中》' },

  { text: '虚心使人进步，骄傲使人落后。', source: '毛泽东《在中国共产党第八届全国代表大会上的开幕词》' },
  { text: '情况是在不断地变化。', source: '毛泽东《在中国共产党全国宣传工作会议上的讲话》' },
  { text: '我们看事情必须要看它的实质。', source: '毛泽东《星星之火，可以燎原》' },
  { text: '自己动手，克服困难。', source: '毛泽东《开展根据地的减租、生产和拥政爱民运动》' },
  { text: '我们应该老老实实地办事。', source: '毛泽东《在中国共产党全国宣传工作会议上的讲话》' },

  { text: '注重调查！', source: '毛泽东《反对本本主义》' },
  { text: '反对瞎说！', source: '毛泽东《反对本本主义》' },
  { text: '一切结论产生于调查情况的末尾。', source: '毛泽东《反对本本主义》' },
  { text: '只有向实际情况作调查。', source: '毛泽东《反对本本主义》' },
  { text: '必须努力作实际调查。', source: '毛泽东《反对本本主义》' },
  { text: '真理的标准只能是社会的实践。', source: '毛泽东《实践论》' },
  { text: '理论的基础是实践，又转过来为实践服务。', source: '毛泽东《实践论》' },
  { text: '感觉只解决现象问题，理论才解决本质问题。', source: '毛泽东《实践论》' },
  { text: '一切真知都是从直接经验发源的。', source: '毛泽东《实践论》' },
  { text: '离开实践的认识是不可能的。', source: '毛泽东《实践论》' },
  { text: '我们还是老实一点吧！', source: '毛泽东《改造我们的学习》' },
  { text: '实事求是。', source: '毛泽东《改造我们的学习》' },
  { text: '错误常常是正确的先导。', source: '毛泽东《改造我们的学习》' },
  { text: '要有目的地去研究。', source: '毛泽东《改造我们的学习》' },
  { text: '任何一个部门的工作，都必须先有情况的了解。', source: '毛泽东《改造我们的学习》' },
  { text: '我们如果有缺点，就不怕别人批评指出。', source: '毛泽东《为人民服务》' },
  { text: '要看到成绩，要看到光明，要提高我们的勇气。', source: '毛泽东《为人民服务》' },
  { text: '我们要努力奋斗。', source: '毛泽东《为人民服务》' },
  { text: '互相关心，互相爱护，互相帮助。', source: '毛泽东《为人民服务》' },
  { text: '为人民的利益坚持好的，为人民的利益改正错的。', source: '毛泽东《为人民服务》' },
  { text: '兵民是胜利之本。', source: '毛泽东《论持久战》' },
  { text: '一切事情是要人做的。', source: '毛泽东《论持久战》' },
  { text: '坐着不动，只有被灭亡。', source: '毛泽东《论持久战》' },
  { text: '要分胜负，还须加上主观的努力。', source: '毛泽东《论持久战》' },
  { text: '执行有利决战，避免不利决战。', source: '毛泽东《论持久战》' },
  { text: '言必信，行必果。', source: '毛泽东《中国共产党在民族战争中的地位》' },
  { text: '埋头苦干。', source: '毛泽东《中国共产党在民族战争中的地位》' },
  { text: '只有实事求是，才能完成确定的任务。', source: '毛泽东《中国共产党在民族战争中的地位》' },
  { text: '只有远见卓识，才能不失前进的方向。', source: '毛泽东《中国共产党在民族战争中的地位》' },
  { text: '每天都是民众的学生。', source: '毛泽东《中国共产党在民族战争中的地位》' },
  { text: '不解决方法问题，任务也只是瞎说一顿。', source: '毛泽东《关心群众生活，注意工作方法》' },
  { text: '我们不但要提出任务，而且要解决完成任务的方法问题。', source: '毛泽东《关心群众生活，注意工作方法》' },
  { text: '应该讨论，应该决定，应该实行，应该检查。', source: '毛泽东《关心群众生活，注意工作方法》' },
  { text: '采取耐心说服的工作方法。', source: '毛泽东《关心群众生活，注意工作方法》' },
  { text: '干就是学习。', source: '毛泽东《中国革命战争的战略问题》' },
  { text: '不同质的矛盾，只有用不同质的方法才能解决。', source: '毛泽东《矛盾论》' },
  { text: '过程变化，旧过程和旧矛盾消灭，新过程和新矛盾发生。', source: '毛泽东《矛盾论》' },
  { text: '用不同的方法去解决不同的矛盾。', source: '毛泽东《矛盾论》' },
  { text: '一切过程都有始有终。', source: '毛泽东《矛盾论》' },
  { text: '星星之火，可以燎原。', source: '毛泽东《星星之火，可以燎原》（引语）' },
] as const

export const quotes: readonly (string | null)[] = [
  ...englishQuotes,
  ...chineseQuotes.map((quote) => quote?.text ?? null),
]

export function quoteSource(id: number): string | undefined {
  return chineseQuotes[id - englishQuotes.length]?.source
}

export function isActiveQuote(id: number): boolean {
  return Number.isInteger(id) && id >= 0 && id < quotes.length && quotes[id] !== null
}

export function quoteForDate(date: string, rejectedIds: number[]) {
  const [year, month, day] = date.split('-').map(Number)
  const dayNumber = Math.floor(Date.UTC(year, month - 1, day) / 86_400_000)
  const rejected = new Set(rejectedIds)
  const isChineseDay = dayNumber % 2 === 0
  const preferredStart = isChineseDay ? englishQuotes.length : 0
  const preferredLength = isChineseDay ? chineseQuotes.length : englishQuotes.length
  const otherStart = isChineseDay ? 0 : englishQuotes.length
  const otherLength = isChineseDay ? englishQuotes.length : chineseQuotes.length
  const dayInLanguage = Math.floor(dayNumber / 2)

  for (const [start, length] of [[preferredStart, preferredLength], [otherStart, otherLength]]) {
    const firstIndex = ((dayInLanguage * 37) % length + length) % length
    for (let offset = 0; offset < length; offset++) {
      const id = start + (firstIndex + offset) % length
      const text = quotes[id]
      if (!rejected.has(id) && text) return { id, text, source: quoteSource(id) }
    }
  }
  return null
}
